### ISSUE TITLE
[Bug] Manual modification of session_id from session manager table

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#196]
If I go to this part of the workflow

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/afb63991-afb8-4541-b292-2d349b7fc34d)

then I interact with the table and change the name of the session like so

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/22fc299f-3823-4ed2-b3f9-34d58bbc4f94)

then my entire pipeline breaks like so on the next page (and this applies if I had retroactively gone back to the session manager after filling in later parts of the pipeline, in which case all my data entry was lost)

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/e95a37c3-1c8e-497f-bcc8-55ddb716005d)

Definitely a highish priority to fix this

Right now, 2 avenues for fixing this

1) desired behavior would be for the values of the session ID field to match the downstream forms (if downstream forms changed) or otherwise if I go back and change them in the session manager that change should also propagate to the form

2) OK, (1) is a bit complicated. For now feel free to just make that cell non-editable (if that's possible or easier, which I assume it is) so that it can't be modified in a way that causes this issue

**Comment by garrettmflynn** [comment]
This was a pretty easy fix in #198. I was clearing removed sessions from the results of each subject and, if no sessions were left on the object, deleting the object that represents that subject. 

However, if you replace the existing session with one or more that are named differently, this would remove the subject and fail to re-instantiate it with the new sessions. That's why no subjects were visualized on the next page.

As such, this should be a fairly localized issue. Let me know if it's working for you.
