### ISSUE TITLE
Subject table page should enforce metadata requirements

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#229]
As it stands now, the subject metadata page does not force the user to adhere to subject requirements, so the user is forced to potentially enter this many times later on the session page. I'd rather make the user enter any required information earlier so it only needs to be entered once. I also would rather not fill in information if we don't know it.

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/f3b46877-732e-4aa8-8a0c-72a18bb416f5)

* sex should be blank by default and should be red
* age and date of birth should be red
* description should be blank

**Comment by CodyCBakerPhD** [comment]
default values for subject description and sex fixed in https://github.com/catalystneuro/neuroconv/pull/480

> age and date of birth should be red

That was pretty tricky to implement in the downstream form, so just a heads up it might take a bit of time to incorporate to the table interactions

**Comment by CodyCBakerPhD** [comment]
Also, it just occurred to me... isn't `age` a session-specific value? What if it's a chronic experiment and the subject has multiple sessions spread out over weeks? The age would change for each session and so the global table wouldn't really apply in that case

**Comment by garrettmflynn** [comment]
That's a great point, Cody. If there's only one session, it's convenient to provide a specific age value on the table—otherwise the age value is likely to change and DOB, as long as we know it, would guarantee a stable representation. However, at least with the Huszar and Valero conversions, a loose range (e.g. P3W-P5W) is specified that does satisfy a "global" age across sessions, even across subjects.

Overall, there doesn't seem to be an elegant way we can have two ways to meet one requirement (e.g. defining a subject's age), so we seem stuck with continuing to apply conditional requirements as we'd done in the JSONSchemaForm.

Are there any other alternatives that you can think of?

**Comment by CodyCBakerPhD** [comment]
> However, at least with the Huszar and Valero conversions, a loose range (e.g. P3W-P5W)

Hah, saved by under-specificity



> so we seem stuck with continuing to apply conditional requirements as we'd done in the JSONSchemaForm.

Yeah, I guess so then

**Comment by garrettmflynn** [comment]
> Also, it just occurred to me... isn't `age` a session-specific value? What if it's a chronic experiment and the subject has multiple sessions spread out over weeks? The age would change for each session and so the global table wouldn't really apply in that case

Because of the quoted comment, do we actually want to implement the check for the required properties here? Should be as simple as switching `validateEmptyCells` to `true` on this Table instance—though that would also mean that users may be blocked if they'd like to specify session-specific age (and don't know to input a temporary cross-session value here)

**Comment by CodyCBakerPhD** [comment]
Validation earlier is better to prevent lots of corrections later in the event there are lots of sessions with an invalidation discovered later

Convenience: top-level table, one or more sessions per day per subject but only one days worth of sessions; can specify all subject info for all sessions from one common place

This also applies if there are multiple days of sessions per subject but age is not known at daily resolution

Potentially incorrect: if more than one day of sessions per subject, the single age value in the top table is actually wrong if the daily age (e.g., `P3W5D`) is specified

Most accurate: only include subject age at the session-level form and require user to add it. Most inconvenient if lots of sessions for a single subject within a single day or low age resolution

So the decision, broadly, is whether we want the most convenient thing at price of potentially incorrect data, or if we place value on accuracy above convenience (convenience as measured by requiring less typing into fewer fields over the forms)

**Comment by garrettmflynn** [comment]
You got it. Great summary of the problem and its scope.

**Comment by CodyCBakerPhD** [comment]
This should be resolved now through a series of past PRs
