### ISSUE TITLE
Tutorial requires 1 GB download of test data using datalad and git-annex

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#352]
Running the tutorial requires downloading the 1 GB "ephy_testing_data" directory from gin using datalad and git-annex. Most novice users will not have datalad or git-annex installed, and so this is a barrier to entry. 1 GB is also a lot of data. Ultimately, GUIDE generates a 49 MB directory of test SpikeGLX and Phy data for two subjects and two sessions per subject. This is totally fine for development. What do you think about packaging the ~50 MB tutorial data with GUIDE, or having GUIDE download the tutorial data automatically when you click "Download Test Dataset" instead of clicking "Generate Dataset"?

**Comment by CodyCBakerPhD** [comment]
> Running the tutorial requires downloading the 1 GB "ephy_testing_data" directory from gin using datalad and git-annex

`datalad` and `gin` both allow lazy/partial  loading so you only need to download the spikeglx and phy respectively (the ~50 MB)



>  Most novice users will not have datalad or git-annex installed, and so this is a barrier to entry.

This link: https://drive.google.com/drive/folders/11Op9GRJSwuBrvyGamQtSVvkYj9BUcHf3?usp=sharing

was shared with the User Days folks and has also been floating around other places, and would be shared with upcoming alpha testers



> What do you think about packaging the ~50 MB tutorial data with GUIDE

Not good GitHub practice to include that much data, even if it is convenient. This repo's history is also already massive enough (might eventually prune if I get the time and we have a downturn on # of active branches to avoid disruption)

However, we don't need to package the bulk binary/npy, they're just noise. So all we would need are the headers.

When we add the SpikeGLXConverter (simple mode of interface selection vs. advanced single-stream) I was planning on adding one header file (~kB sized) to this repo and then writing some code to generate multi-probe multi-segment SpikeGLX example on the fly

IDK if that will be ready for alpha testing, I'd say the link above ought to be more than sufficient



> having GUIDE download the tutorial data automatically when you click "Download Test Dataset"

I am against adding `datalad` to the already massive environment bundle just for this purpose

We also have no well established (tested) automated methods for performing this for users, unlike every other operation we expose

Installing `git-annex` is also a pain on certain platforms - this is why our CI actually uses an S3 bucket that has a copy of the `ephy_testing_data` on it, but I would not ask users to download from that due to data transfer costs

**Comment by rly** [comment]
> > Running the tutorial requires downloading the 1 GB "ephy_testing_data" directory from gin using datalad and git-annex
> 
> `datalad` and `gin` both allow lazy/partial loading so you only need to download the spikeglx and phy respectively (the ~50 MB)

Ah, good to know.

> 
> > Most novice users will not have datalad or git-annex installed, and so this is a barrier to entry.
> 
> This link: [drive.google.com/drive/folders/11Op9GRJSwuBrvyGamQtSVvkYj9BUcHf3?usp=sharing](https://drive.google.com/drive/folders/11Op9GRJSwuBrvyGamQtSVvkYj9BUcHf3?usp=sharing)
> 
> was shared with the User Days folks and has also been floating around other places, and would be shared with upcoming alpha testers

Thanks! Sorry I missed this. What do you think about updating the tutorial text to say to download this google drive folder instead of from datalad? We could pre-zip the folder for easy download too.

> 
> > What do you think about packaging the ~50 MB tutorial data with GUIDE
> 
> Not good GitHub practice to include that much data, even if it is convenient. This repo's history is also already massive enough (might eventually prune if I get the time and we have a downturn on # of active branches to avoid disruption)
> 
> However, we don't need to package the bulk binary/npy, they're just noise. So all we would need are the headers.
> 
> When we add the SpikeGLXConverter (simple mode of interface selection vs. advanced single-stream) I was planning on adding one header file (~kB sized) to this repo and then writing some code to generate multi-probe multi-segment SpikeGLX example on the fly
> 
> IDK if that will be ready for alpha testing, I'd say the link above ought to be more than sufficient

Sounds good.

> 
> > having GUIDE download the tutorial data automatically when you click "Download Test Dataset"
> 
> I am against adding `datalad` to the already massive environment bundle just for this purpose
> 
> We also have no well established (tested) automated methods for performing this for users, unlike every other operation we expose
> 
> Installing `git-annex` is also a pain on certain platforms - this is why our CI actually uses an S3 bucket that has a copy of the `ephy_testing_data` on it, but I would not ask users to download from that due to data transfer costs

Oh yes, I totally agree. I meant download from google drive / S3 / another host via a new mechanism, e.g., `curl` or `requests`. But having people click a google drive link and download that locally is easy enough.

**Comment by CodyCBakerPhD** [comment]
> What do you think about updating the tutorial text to say to download this google drive folder instead of from datalad?

The drive folder is temporary and not guaranteed to be persistent, whereas the ground truth GIN repo is, so I wouldn't want to build it into anything yet


> We could pre-zip the folder for easy download too.

Cross-platform zipping is a pain. For maximum usability would need a separate native zip from/to each platform. Also not sure how much space it would actually save given most of the 'data' is just noise (and you can download the entire folder directly from Drive anyhow, surely ~50 MB is small enough to not need compression)


> Oh yes, I totally agree. I meant download from google drive / S3 / another host via a new mechanism, e.g., curl or requests.

If you know a bug-free cross-platform native command for that and could get it integrated in a small amount of time, that would indeed be more convenient. But that sounds like a somewhat complicated feature and would need CI tests as well, so again IDK about building it into the app in that way


How about this - it seems the simplest approach is what I say about hosting the core template metadata files (~KB scale) on this repo and ship it with the GUIDE

Then I assign you to put together an API endpoint to deterministically generate the SpikeGLX structure seen in [this multi-gate multi-probe example](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/spikeglx/multi_trigger_multi_gate/SpikeGLX/5-19-2022-CI0) (via numpy, or SI is also in our GUIDE environment so feel free to use its more pattern-based generation tools; don't forget to modify the copied metadata files for each stream appropriately to match the ground truth exactly)

Then we'll tackle Phy similarly after that. How does that sound?

**Comment by garrettmflynn** [comment]
Completed with #218
