### ISSUE TITLE
[Windows]: Vite and 'export' command

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#42]
While I was away at the conference I mostly worked from my laptop (M1 Mac)

Now that I'm back I tried some of the latest changes on Windows, and ran into this error from the typical workflow

```
npm ci
npm start
```

(from fresh environment of course), resulting in

```
vite v4.1.4 building for production...
transforming (245) node_modules\sweetalert2\src\utils\dom\renderers\renderCloseButton.jsUse of eval in "node_modules/lottie-web/build/player/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 250 modules transformed.
dist/index.js  2,790.21 kB │ gzip: 458.98 kB
'export' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by garrettmflynn** [comment]
Got it. This is unrelated to Vite and, instead, is triggered by the start command:
```
npm run build && export ENABLE_CORS=false && npm run start:electron
```

I'm trying to toggle between enabled and disabled Cross-Origin Resource Sharing (CORS) when using `npm start` vs `npm dev`. However, it looks like `export XXX` is only supported in UNIX shells. 

Do you know of other ways to set this environment variable per command-line call? Otherwise, it wouldn't be terrible always to have it enabled / configurable from a .env file—though it doesn't need to be enabled when the Flask server is run with Electron.

**Comment by CodyCBakerPhD** [comment]
> Do you know of other ways to set this environment variable per command-line call? Otherwise, it wouldn't be terrible always to have it enabled / configurable from a .env file

The simplest way would likely be separate `npm` commands for windows, since it's only me that uses it
