### ISSUE TITLE
`tifffile` missing from distributable

### ISSUE THREAD

**Issue by weiglszonja** [NeurodataWithoutBorders/nwb-guide#421]
**Describe the issue**
I was trying to use `MicroManagerTiffImagingInterface` in the conversion, but received an error after providing the source data, that `tifffile` is not installed.

**Operating system used:**

- OS: Macbook M2

**Additional context**

<img width="1512" alt="Screenshot 2023-10-03 at 18 11 53" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/24475788/e4f0cc68-ea5f-4fe0-aaa0-3e712aa5591e">

**Comment by CodyCBakerPhD** [comment]
Also seen by Vincent in #494

**Comment by CodyCBakerPhD** [comment]
@vncntprvst What platform were you using when you saw this error?

**Comment by bendichter** [comment]
He was use a Windows computer

**Comment by CodyCBakerPhD** [comment]
FYI for anyone that ever runs into this issue, e.g., @vncntprvst

The simplest fix is just to re-install the application using the [developer installation instructions](https://nwb-guide.readthedocs.io/en/latest/developer_guide.html#developer-installation) instead of using the released distributable

This will require an existing conda installation, which should be the only added inconvenience - but it will certainly resolve the import issue

We'll continue to try to fix this in the official build of course, but no ETA on when it might be ready

**Comment by vncntprvst** [comment]
Thank you Cody!
