### ISSUE TITLE
Separate session management from global subject table

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#482]
Also resolve that outstanding issue with adding new sessions to the pipeline from Bens

**Comment by garrettmflynn** [comment]
Just to provide some more details for my sake here:
1. We are splitting the Subject Table into two tables: a Subject Metadata table (with Subject ID as a main column) and a Session ID table where each Session ID is associated with one Subject ID (constrained to exising IDs).
2. This helps people think in terms of standard input cells whenever they use our tables (rather than the CSV-like list editor).
3. When changing the Subject ID, it should auto-update on the second table

**Comment by CodyCBakerPhD** [comment]
While the current method of manually adding more sessions could be improved in separate ways, I'd say this separation is no longer needed
