### ISSUE TITLE
Package for conda-forge

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/nwb-guide#552]
**Is your feature request related to a problem? Please describe.**

ATM installation is "old fashion" - download some binary blob from somewhere and install. Not sure how updates are implemented (may be built in)... not sure if libraries like dandi are bundled or also need to be installed separately.. if bundled -- how to be upgraded for fixes?
 
**Describe the solution you'd like**

integrate/package for distributions.

conda is a popular distribution.

conda-forge already has https://anaconda.org/conda-forge/electron and dandi and many other modules.
You already have https://github.com/NeurodataWithoutBorders/nwb-guide/blob/8da7ebe50a1c7aa5a64c0d293b459bdf413630be/environments/environment-Linux.yml and alike

So I think it should be quite easy to prepare a feedstock recipe. See e.g. one for dandi: https://github.com/conda-forge/dandi-feedstock/blob/main/recipe/meta.yaml

**Additional context**

life is short

edit: inspired by https://github.com/dandi/helpdesk/discussions/36#discussioncomment-7999281

**Comment by CodyCBakerPhD** [comment]
https://anaconda.org/conda-forge/electron is just the tool for doing the building, not an actual instance of a built application - there is no actual package here to be supported on conda or PyPI (nor is there truly any GUIDE module that could be imported by another project - just a small collection of basic utility functions that no one else is really intended to use)

All our installations for Mac and Windows are done via the executables/.dmg on the [releases page](https://github.com/NeurodataWithoutBorders/nwb-guide/releases) - linux is a special case that only supports dev installation (`git clone`, `conda create -f`, and `npm ci`)

Under the hood this is the result of bundling all the frontend JS/TS/CSS components and assets into the pages, various actions on which send REST queries to a back-end Flask server that is launched by bundling each platform specific 'nwb-guide' conda environment into a single Python executable using PyInstaller; the versions of all constituent packages referenced by that executable are frozen to what was configured at the time that executable was built by the automated workflow

When running the app in dev mode however the backend executable is not compiled and the backend relies on the living conda environment that you can actively install and modify various versions of any dependencies - but the 'package' of the GUIDE in any sense would simply be the Flask server and its endpoints, which are essentially just wrappers around NeuroConv functions and workflows

We have discussed some long-term plans to support custom user-defined backends for certain operations, such as custom defined interfaces, docker containers, etc. but still, these would be installed/setup in a plugin fashion independently of the main app and the app itself only configured to look at those ports for custom additions - those plugins could theoretically exist on conda or PyPI, but we don't have working examples or guarantees of how that would work yet

> how to be upgraded for fixes?

The app itself would be upgraded in this case

electron has some auto-alert functionality for this, currently suppressed due to what I recall was a bug (maybe @garrettmflynn remembers more clearly), we could definitely consider re-enabling it when we get a second to smooth it out - it basically checks every time you launch the app if there is a newer version released if you'd like to update your current installation (single button yes/no)

So for package upgrades/fixes or more importantly, DANDI upload version compatibilities with the live service, we'd simply trigger a rebuild and minor version bump for the app to have the most up-to-date dependencies on the backend

**Comment by CodyCBakerPhD** [comment]
I'll also add the main point of this project is to supply Windows/Mac users with a conda/python (even command-line) free approach to doing the conversion; as such there isn't much need to have a conda or PyPI installation pathway even if it were possible for this style of application

Oh, we'll also be adding a Zenodo source of the setup executables soon, if that satisfies the core of the issue (it will also provide us with a DOI on the software for people to cite)
