### ISSUE TITLE
Experimenter name validation is too restrictive

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#594]
The following names fail name validation:
Kyu Hyun
Yang-Sun
György

Can we use the [dandi schema name pattern](https://github.com/dandi/dandi-schema/blob/c3a74ccffe66329876d73481b0846793f1e3d744/dandischema/models.py#L41)?
`r"^([\w\s\-\.']+),\s+([\w\s\-\.']+)$"`

For example:
Mitášová, Helena
O'Brien, Claire
Last, First A

**Comment by garrettmflynn** [comment]
It's easy enough to switch these out. However, the DANDI pattern will allow names that don't have capital letters to start. That is fine?

I'm also noticing that this regex supports special characters (e.g. in `Mitášová`) for Python, but doesn't when used in JavaScript. I've modified it so that letters from any language are matched.

Finally, it doesn't seem like DANDI handles middle names / initials as rigorously as we otherwise are. Do we still want all three possible inputs? We can also just show a single input for full name.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn I'm not sure if there's an extra regex layer on top of this in the forms, but there's also the NWB Inspector check for this: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/checks/nwbfile_metadata.py#L63

which you could just rely on if you just form the "<Lastname>, <Firstname> <MiddleName pattern>" for the `experimenter` field

**Comment by garrettmflynn** [comment]
Yeah both are actually used. For the construction of the name, we have a pop-up form separating First, Middle, and Last Names, then these are connected with `, ` and this final result is checked against NeuroConv.

**Comment by CodyCBakerPhD** [comment]
OK so the part that was too restrictive was the front end part, not the Inspector check?

**Comment by garrettmflynn** [comment]
Yes exactly. Not sure where I came up with the original regex, I think it was just an extension of the returned error message from NWB Inspector (which implies everything must be capitalized).
