### ISSUE TITLE
Adding keywords one by one is tedious

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#602]
Observed in two of the recent user tests. One tried entering keywords as a comma-separated string. The other entered several of them one by one and it seemed pretty tedious. A comma-separated string seems the most intuitive to me. I can't think of a keyword that includes a comma within it.

**Comment by CodyCBakerPhD** [comment]
> A comma-separated string seems the most intuitive to me.

Knowing to separate entries with a manual comma was the original implementation of that field, but was itself confusing and didn't give very good results or feel intuitive during early tests

To clarify, you were testing against a version that looks like this?

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/98862cf4-5616-4e0c-b702-0cf0f936e354)

(with that bottom one in the process of being dragged up above the second, hence the extra floating text)

Yes, it requires several more clicks, but at least it explicitly communicates how separate entries behave

For comparison, the DANDI website does this on a single line but uses the tab character to 'seal in' (visually wraps entries in gray bubble) what a user types, which itself is very frustrating because it doesn't support editing in any way (you have to delete and retype anything to adjust or correct typos)



> I can't think of a keyword that includes a comma within it.

Yet it is technically possible to do so in the NWB file, since each entry is a separate string. If you want to discourage it then it would have to become an Inspector check and would be something validated on each entry here

**Comment by garrettmflynn** [comment]
We could also bake in an `Add an Entry` feature in the pop-up that is attached to the list, so that you could generate a 2nd (or nth) input to add more keywords without closing the modal.

**Comment by CodyCBakerPhD** [comment]
@rly I believe the UI for this has evolved over time, can you give it a whirl and see if this can be closed?

**Comment by rly** [comment]
Sorry for the delay. I'll take a look

**Comment by rly** [comment]
The new UI looks great. Can we make it so that pressing enter in that text box submits the keyword, so I don't need to click "Submit" each time?
