### ISSUE TITLE
[Feature]: Hiding form hints until Submit

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#636]
### What would you like to see added to the NWB GUIDE?

For example, I find this amount of red in a form to be unsettling:

<img width="1292" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/b87cdc96-780e-4c48-8de7-7adfce4d1847">

Can we please alter this so that the "hints" that appear below each text field only pop up after you hit "Create" with invalid inputs?

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Specifically, the request seems to be to not display error flags for fields that are, in some cases, default in an error state (usually because missing when required)

I believe this results because it is the common mechanism of any error to display the flag explaining that error

@garrettmflynn Question is, how hard would this be to separate from the normal behavior of user typing in an input and the flag only being displayed on invalidation of that input?

**Comment by bendichter** [comment]
Yeah, I think technically speaking what I want is to skip validation a first and then apply validation either when a user deselects a field or when a user its submit (or similar).

**Comment by garrettmflynn** [comment]
This was already implemented in https://github.com/NeurodataWithoutBorders/nwb-guide/pull/632, we just haven't merged it in yet 😅

**Comment by CodyCBakerPhD** [comment]
Looks like @bendichter approved it but then someone forgot to hit the merge button

closed with #632, reopen otherwise
