### ISSUE TITLE
Upload summary Files uploaded

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#658]
### Describe the issue

Using the independent Upload feature

<img width="1111" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/a7d67499-a712-48e9-8d5e-6e01b13da827">

Here under Files Uploaded, it lists a directory, not files.

### Steps to Reproduce

see above

### Operating System

OSX

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by garrettmflynn** [comment]
From the GUIDE, it's difficult for me to know _exactly_ what folders and files were successfully uploaded to DANDI. This doesn't seem to be returned from the `automatic_dandi_upload`.

@CodyCBakerPhD Could you have this function return a list of successfully uploaded file paths? If not, I'll need a description of the strategy for discovering files to upload, so this can be replicated on the GUIDE end.

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD Could you have this function return a list of successfully uploaded file paths? 

Give this a try: https://github.com/catalystneuro/neuroconv/pull/773

This indirectly assumes that if there was an error during upload, it would raise in the `stderr` and not return anything, and therefore if it returns something it means it uploaded successfully

Otherwise the `upload` function via the DANDI API does not itself indicate such success/failure
