### ISSUE TITLE
[Feature]: Single session - Source data and File Metadata

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#685]
### What would you like to see added to the NWB GUIDE?

<img width="990" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/3851c2ab-4824-4106-a2d5-9287edb685c0">

For this page, since there is only one session, there is no need for the "Sessions" menu. I think this should be removed, and we should just have the "Phy Sorting" and "SpikeGLX Converter" accordions. The same logic applies to the "File Metadata" page.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by oruebel** [comment]
In this case I would personally vote for consistency of the interface, rather than trying to oversimplify. While the Sessions listing is not strictly necessary when there is only 1 Session, it may not be obvious for a user why that column is there sometimes when they do conversions and not present at other times. I.e., hiding the column may seem more like a bug to a repeat user rather than a feature.

**Comment by bendichter** [comment]
@oruebel this would only apply to the single session workflow, where a user has chosen the option that says they are only converting a single session.

**Comment by garrettmflynn** [comment]
An example of this UI change can be seen on the Inspector Report and Conversion Preview pages, which encapsulate the results in an "InstanceManager" based on the number of sessions.
