### ISSUE TITLE
[Feature]: Minor suggestions for tutorial

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#717]
### What would you like to see added to the NWB GUIDE?

The single session tutorial runs really nicely! Great work @CodyCBakerPhD @garrettmflynn !!

I have a few minor suggestions:

1. On the dataset generation page,
<img width="748" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/754e158c-6ec6-4d19-9187-e3c7b08b6420">
I think the italicized text would look better as code instead of italics. Same for in the single session tutorial page.

2. In the [single session tutorial](https://nwb-guide.readthedocs.io/en/latest/tutorials/single_session.html)
"Upon launching the GUIDE, you’ll begin on the Conversions page."
"Conversions" -> "Convert"? There is no page named "Conversions". I'm sure people will figure it out but it's nice to have a 1:1 match.

3. Under "Project Setup", the "Note" seems like a lot of detail and not critical for the tutorial
<img width="757" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/8f041686-1044-4a0b-bb4f-42061a8a233d">

4. "NeuroPixel" -> "Neuropixels"

5. "with an age of P30D." ->
"with an age of P30D, which represents 30 days old"

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
> the italicized text would look better as code instead of italics.

It should have been. Very common mistake since italics is a single backtick whereas code is double

Can you open a PR for that?

**Comment by CodyCBakerPhD** [comment]
> Under "Project Setup", the "Note" seems like a lot of detail and not critical for the tutorial

The second point is extremely important for using the GUIDE on their own data however, so I would rather they get exposed to it sooner rather than later. Otherwise our app could overload their system (no current stress tests to ensure ample disk space is available beyond what we hope h5py/zarr would normally do)

The tutorial itself will not have this problem of course (unless they are REALLY full already on home drive - has been seen in occasional user tests...)

The point about SSD is also a think to know earlier rather than later, and counters user concerns over write speed (even applying to the tutorial)
