### ISSUE TITLE
Entire screen is auto selected/highlighted on click to 'next page'

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#739]
### Describe the issue

Screenshot shows one example of what it's like, but every time I proceed to the next page of a pipeline in the app all the text fields are automatically selected as if I had dragged my mouse over it

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/93a19acf-209f-4984-be10-43fddbeaea7c)

@garrettmflynn have you ever seen this before?

### Steps to Reproduce

Hit the 'next' button on any page of a pipeline

### Operating System

Windows

### GUIDE Version

0.0.15

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
This is just a quality of life oddity I recently noticed, not a huge priority I suppose

**Comment by garrettmflynn** [comment]
Yeah I see this all the time, guess I just never talked about it.

It's a result of having everything selectable as per @bendichter's request. 

Making text selectable in any way seems to have unintentional consequences like this. This happens when all is selectable, and per-element selectability tends to result in persistent blue highlights—which are unintentional but at least a result of a specific user action.

**Comment by garrettmflynn** [comment]
Could get a short-term fix out in just a couple minutes. But that disables all selectability.

**Comment by rly** [comment]
I also like having everything selectable for bug reporting and I think in general people expect to be able to select and copy text. The main issue I have experienced is when all text is selected, then pressing Back/Next does not unselect the text. What if anytime you navigate to a new page, all text gets unselected?

**Comment by garrettmflynn** [comment]
Sure I'll give this a shot. I've had to do something similar on the E2E tests; just never nailed down this behavior through manual interaction.
