### ISSUE TITLE
Iterate over sessions

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#78]
The most important feature we probably need at this point is automated iteration over a parent folder of multiple sessions; some experiments have hundreds of sessions, so it is totally unfeasible to ask people to repeat our convenient process that many times

We've been discussing this largely in Figma so far, which we probably still should as the mockups become more detailed, but opening this issue to keep official track of priorities

Also probably going to intimately entangle development of this feature on the GUIDE with [this feature branch of NeuroConv (#377)](https://github.com/catalystneuro/neuroconv/pull/377)

**Comment by garrettmflynn** [comment]
Here's an updated list of all the required behaviors the Session Manager will need to link into other GUIDE features appropriately:
1. Render sub-properties of the JSONSchemaForm within accordions (rather than #122)
2. Add a Preview button to allow users to preview a single session at any time
 - On the next page, select a random session and generate the preview for explicit confirmation
3. Add an indicator on the sidebar for whether a single session's requirements are met
4. Render manager-level notifications (e.g. "x sessions are not valid") before individual session notifications ("session x has y problems")
5. When adding a new interface, ensure old user-specified metadata is maintained + merged rather than overwritten.

**Comment by CodyCBakerPhD** [comment]
Done after a series of PRs
