### ISSUE TITLE
[Feature]: Feedback from first time users at StratNeuro tutorial

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/nwb-guide#838]
### What would you like to see added to the NWB GUIDE?

Here's some feedback we collected from users trying out GUIDE for the first time, basically following the tutorials in the documentation:
- some errors (validation errors) happen but disappear after closing / opening the software
- neroconv version 0.4.9 yields a validation error, we should pin the official linux installation to a released version of neuroconv
- sometimes files / folders paths are not found
- autosaving of pipelines is not working
- more descriptive error messages
- tooltips on hover might help make sense of some actions throutghout the pipeline
- some systems do not allow for admin privileges

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Thanks for keeping track of as much of this as possible

> some errors (validation errors) happen but disappear after closing / opening the software

We would need some specific examples to reproduce please


> neroconv version 0.4.9 yields a validation error, we should pin the official linux installation to a released version of neuroconv

Using `linux-latest` or `linux-dev`? `0.4.9` was also released yesterday; what is the specific validation error that you see?


> sometimes files / folders paths are not found

Would love to know the platform, data source (external USB?), or anything else to try to reproduce


> autosaving of pipelines is not working

Can you give specific examples? Also what platform?


> more descriptive error messages

These have generally been improved on `main` / official release


> some systems do not allow for admin privileges

Such as?

UNIX would use `sudo` (if user has `sudo` of course, not much point in doing any of this otherwise since they won't have permission to do much related to file I/O except on very special mounts)

Windows likewise has 'run as administrator'; again, without that it's very tricky to properly expose file system access for reading/writing files throughout the entire process

**Comment by CodyCBakerPhD** [comment]
Let us know if any of these reoccur over time with the official release; an individual ticket for each bug together with details steps to reproduce would help us a lot

Thanks
