### ISSUE TITLE
Select SpikeGLX test data

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-guide#852]
### Describe the issue

When selecting `~/NWB_GUIDE/test-data/single_session_data/spikeglx/Session1_g0/Session1_g0_imec0` from the test data, as indicated in the tutorial https://nwb-guide.readthedocs.io/en/v1.0.0/tutorials/single_session.html#source-data-information, I get the following error:

![Screen Shot 2024-06-10 at 1 34 33 PM](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/10999845/b7f54699-ed7d-4b27-93ec-4b40e79f2009)

If I select the parent folder ``~/NWB_GUIDE/test-data/single_session_data/spikeglx/Session1_g0` instead GUIDE is able to continue. Maybe this is just something that should be updated in the docs?

### Steps to Reproduce

- Generate the test data
- Select "Spike GLX" with `~/NWB_GUIDE/test-data/single_session_data/spikeglx/Session1_g0/Session1_g0_imec0` 

### Operating System

MacSO

### GUIDE Version

1.0

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by rly** [comment]
The error suggests that you put the directory
```
~/NWB_GUIDE/test-data/single_session_data/spikeglx/Session1_g0/Session1_g0_imec0/Session1_g0_imec0_imec0
```
instead of
```
~/NWB_GUIDE/test-data/single_session_data/spikeglx/Session1_g0/Session1_g0_imec0/
```

The directory that you put should not exist. Could you share a screencast of selecting the above folder?

**Comment by rly** [comment]
Wait a second - the SpikeGLX Recording interface asks for a File Path, not a Folder. Are you sure you selected "SpikeGLX Recording" not "SpikeGLX Converter"?

**Comment by CodyCBakerPhD** [comment]
It's a common mistake in the current tutorial; careful followers will choose the 'SpikeGLX Recording' (single-stream) for the single file path, but it is not the first item that pops up when you search 'SpikeGLX'

We've discussed it previously since it was seen in user testing, but I've added it to the list on #846 so it's on the record

An improvement might just be to have a separate tab for 'advanced' interfaces, which this one might qualify as since the 'SpikeGLX Converter' 

This could remove ambiguity for various formats that have multiple interfaces
