### ISSUE TITLE
Problem installing NWB Guide on Linux remote server

### ISSUE THREAD

**Issue by emosb** [NeurodataWithoutBorders/nwb-guide#894]
### Describe the issue

When trying to install python dependencies on our remote server, we ran into a disk quota error initially (as our home location on the remote server allows only 1GB of memory).

### Steps to Reproduce

To create the environment in another location with more memory, we added a --prefix command (see command line prompt below):

```
conda create --file ./environments/environment-Linux.yml --prefix /projects/LEIFER/Emily/nwb-guide
```

but this generated the following error:

```
CondaValueError: could not parse 'name: nwb-guide' in: ./environments/environment-Linux.yml
```

### Operating System

Linux

### GUIDE Version

Linux branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Thanks @emosb

For context, we discovered this during a joint meeting for the Leifer project

I think the solution would be to remove the hardcoded naming in our environment files, since that seems to be the incompatibility. The dev install instructions would need to be adjusted to call `conda create --name` instead of `conda env create` (which does not support `--name` or `--prefix`) with extra instructions for using `--prefix` instead of `--name` (which are not jointly compatible)
